<!--
    Copyright 2012-2018 Robert Pinchbeck
  
    This file is part of AbnfToAntlr.

    AbnfToAntlr is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    AbnfToAntlr is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with AbnfToAntlr.  If not, see <http://www.gnu.org/licenses/>.
-->

<%@ Page Language="C#" AutoEventWireup="True" CodeBehind="Default.aspx.cs" Inherits="AbnfToAntlr.Web.DefaultPage" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>ABNF to ANTLR</title>
    <style type="text/css">
        .width_120px {
            width: 120px;
        }

        .width_100pct {
            width: 100%;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <h2>ABNF To ANTLR</h2>
        <p>
            Translate any ABNF grammar to an ANTLR grammar. The resulting ANTLR grammar should be syntactically correct; however, some ABNF grammars are inherently ambiguous and ANTLR will complain about them until the ambiguity is resolved by the user.  The translator uses parser and lexer components generated by the excellent ANTLR toolset.  Source code and binaries are available at 
        <a href="https://github.com/rpinchbeck/Abnf-To-Antlr">GitHub</a>.
        </p>
        <asp:Label ID="lblInput" runat="server" Text="ABNF&nbsp;Grammar:"></asp:Label>
        <asp:DropDownList ID="lstStandardGrammars" runat="server" AutoPostBack="True" OnSelectedIndexChanged="lstStandardGrammars_SelectedIndexChanged"></asp:DropDownList>
        <br />
        <asp:TextBox ID="txtInput" runat="server" TextMode="MultiLine" MaxLength="1048576" Height="300" Width="100%" Wrap="False"></asp:TextBox>
        <br />
        <br />
        <asp:Button ID="butTranslate" runat="server" Text="Translate" OnClick="butTranslate_Click" />
        &nbsp;&nbsp;&nbsp;&nbsp;
    <asp:CheckBox ID="chkPerformDirectTranslation" runat="server"
        Text="Direct Translation (do not substitute a lexer rule for each distinct character)" />
        <br />
        <br />
        <asp:Label ID="lblOutput" runat="server" Text="ANTLR&nbsp;Grammar:"></asp:Label>
        <br />
        <asp:TextBox ID="txtOutput" runat="server" TextMode="MultiLine" ReadOnly="True" Height="300" Width="100%" Wrap="False"></asp:TextBox>
        <br />
        <asp:TextBox ID="txtError" runat="server" ForeColor="DarkRed" ReadOnly="True" TextMode="MultiLine" Width="100%"></asp:TextBox>
        <p><i>Version 1.7.1</i></p>
    </form>
</body>
</html>
